In [1]:
import numpy as np
import pandas as pd

In [2]:
fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')

In [3]:
fake.shape

(23481, 4)

In [4]:
true.shape

(21417, 4)

In [5]:
fake.head(5)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [6]:
true.head(5)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

In [7]:
fake["class"] = 0
true["class"] = 1

In [8]:
fake.shape

(23481, 5)

In [9]:
true.shape

(21417, 5)

In [10]:
fake_true = pd.concat([fake,true], axis=0)

In [11]:
fake_true

title  \
0       Donald Trump Sends Out Embarrassing New Year’...   
1       Drunk Bragging Trump Staffer Started Russian ...   
2       Sheriff David Clarke Becomes An Internet Joke...   
3       Trump Is So Obsessed He Even Has Obama’s Name...   
4       Pope Francis Just Called Out Donald Trump Dur...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text    subject  \
0      Donald Trump just couldn t wish all Americans ...       News   
1      House Intelligence Committee Chairman Devin Nu...       News   
2      On Friday, it was revealed that former Milwauk...       News   
3      On Christmas day, Donald Trump announced that ...       News   
4      Pope Francis used his annual Christmas Day mes...       News   
...                                                  ...        ...   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...  worldnews   
21413  LONDON (Reuters) - LexisNexis, a provider of l...  worldnews   
21414  MINSK (Reuters) - In the shadow of disused Sov...  worldnews   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...  worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...  worldnews   

                    date  class  
0      December 31, 2017      0  
1      December 31, 2017      0  
2      December 30, 2017      0  
3      December 29, 2017      0  
4      December 25, 2017      0  
...                  ...    ...  
21412   August 22, 2017       1  
21413   August 22, 2017       1  
21414   August 22, 2017       1  
21415   August 22, 2017       1  
21416   August 22, 2017       1  

[44898 rows x 5 columns]

In [12]:
fake_true = fake_true.sample(frac=1)  #shuffle the dataframe

In [13]:
fake_true.head(15)

title  \
21884  NOT NEWS: [Graphic Video] Michigan Woman Runs ...   
1874   Congressional Democrats back Harvey aid with t...   
19374  Trump, Ghani agree U.S. can help develop Afgha...   
6058   Pressured by Trump, Mexico ready to discuss NA...   
5735    ‘Real Time’ Panelists Discuss Dem Sit-In, Thi...   
2763    The Internet Just Ripped Trump APART For Firi...   
17738  Genocide trial against ex-Guatemalan dictator ...   
1029   Flake's retirement could upend Senate race in ...   
8077   Clinton calls national security team after att...   
13464  WOW! IVANKA TRUMP Was The Best Speech Yet At T...   
11776  SAVAGE ANTI-TRUMP PROTESTERS Knock Out Innocen...   
5510    CNN Panel Breaks Out In CHAOS After Someone C...   
22574  Henningsen on White House Press Dinner: ‘The F...   
20541  Syrian army, allies reach airbase besieged by ...   
11511  Danish police charge Syrian man with attempted...   

                                                    text       subject  \
21884  This is a story that will never make the news....     left-news   
1874   WASHINGTON (Reuters) - Congressional Democrati...  politicsNews   
19374  (Reuters) - U.S. President Donald Trump and Af...     worldnews   
6058   MEXICO CITY (Reuters) - Under pressure from Pr...  politicsNews   
5735   During a panel discussion on Real Time with Bi...          News   
2763   Acting Attorney General Sally Yates refused to...          News   
17738  GUATEMALA CITY (Reuters) - Former Guatemalan d...     worldnews   
1029   (Reuters) - Republican Senator Jeff Flake’s su...  politicsNews   
8077   WASHINGTON/HIGH POINT, N.C. (Reuters) - Democr...  politicsNews   
13464  The expectations were high for Ivanka Trump s ...      politics   
11776  AIRPORTS ACROSS THE COUNTRY were inundated wit...      politics   
5510   CNN s Chris Cuomo tried to have a discussion a...          News   
22574  21st Century Wire says  B ACTING: President Ob...       US_News   
20541  BEIRUT (Reuters) - The Syrian army and its all...     worldnews   
11511  COPENHAGEN (Reuters) - Danish Police have char...     worldnews   

                      date  class  
21884          Apr 9, 2015      0  
1874    September 6, 2017       1  
19374  September 22, 2017       1  
6058     January 24, 2017       1  
5735         June 25, 2016      0  
2763      January 31, 2017      0  
17738    October 11, 2017       1  
1029     October 25, 2017       1  
8077   September 20, 2016       1  
13464         Jul 21, 2016      0  
11776         Jan 30, 2017      0  
5510         July 11, 2016      0  
22574          May 6, 2016      0  
20541   September 9, 2017       1  
11511   December 22, 2017       1

In [14]:
fake_true.isnull().sum()  #to chech that whether there is any null value present or not

title      0
text       0
subject    0
date       0
class      0
dtype: int64

In [16]:
fake_true = fake_true[0:5000]

In [17]:
x = fake_true.iloc[:,:-1].values
y = fake_true.iloc[:,-1].values

In [18]:
x[0]

array(['NOT NEWS: [Graphic Video] Michigan Woman Runs Over Rival With Car Following Street Brawl',
       'This is a story that will never make the news. A woman uses a car to intentionally hit another woman (this is the second time she s used her car as a weapon to hit another human being) but unfortunately, it s just another day of black on black crime, so it doesn t fit the media s narrative A wild fight between two 19-year-olds along a Michigan street Monday came to a dramatic end when one ran over her rival with a car.What began as a fight in the middle of the street with onlookers encouraging   and sometimes interfering   with the one-on-one showdown devolved into a hit-and-run, shocking video shows. Let them fight,  at least one bystander yells repeatedly.Police have issued a warrant for Jalin Smith-Walker, accused of being behind the wheel during the graphic assault, The Grand Rapids Press reported. It was a fight between two former friends. It ultimately ended with blows being

In [19]:
y[0]

0

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000)
mat_body = cv.fit_transform(x[:,1]).todense()

In [22]:
mat_body

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0],
        [0, 2, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
cv_head = CountVectorizer(max_features=15000)
mat_head = cv_head.fit_transform(x[:,1]).todense()

In [24]:
mat_head

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 2, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
x_mat = np.hstack((mat_head,mat_body))

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_mat, y, test_size=0.2, random_state=0)

In [27]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy')
dtc.fit(x_train,y_train)
dtc.predict(x_test)

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,

In [28]:
y_pred = dtc.predict(x_test)

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[317,   3],
       [  3, 277]], dtype=int64)

In [30]:
(317+277)/(317+277+3+3)

0.99